package com.universitycourseproject.service;

import java.util.List;

import com.universitycourseproject.entities.UniversityStaffMember;
import com.universitycourseproject.exception.AlreadyExistException;
import com.universitycourseproject.exception.DataNotFoundException;

public interface UniversityStaffMemberService {
	public UniversityStaffMember addUniversityStaffMember(UniversityStaffMember universityStaffMember)throws AlreadyExistException;
	public UniversityStaffMember removeUniversityStaffMember(int universityStaffMemberId) throws DataNotFoundException;
	public UniversityStaffMember updateUniversityStaffMember(UniversityStaffMember universityStaffMember) throws DataNotFoundException;
	public UniversityStaffMember viewUniversityStaffMember(int universityStaffMemberid) throws DataNotFoundException;
	public List<UniversityStaffMember> viewAllUniversityStaffMember()throws DataNotFoundException;
}
